### ISSUE TITLE
Error:Loading module: provider | No module named xbmc

### ISSUE THREAD

**Issue by f2ca1bb6** [a4k-openproject/script.module.openscrapers#104]
happens when running `scrape-test.py`.

minimal setup to reproduce:

```python
import sys
import os
sys.path.append(os.path.join(os.path.curdir, 'lib'))
from lib import openscrapers
openscrapers.sources(None, True)
```

**Comment by reddit-reaper** [comment]
yeah known issue, only way to bypass is to import mock_kodi to avoid import issues into your python environment to avoid issues. i haven't fixed it yet so it can do that though

**Comment by reddit-reaper** [comment]
we'll also be changing our scraper package soon to v2 so i would just wait on that
