### ISSUE TITLE
dead PL providers 

### ISSUE THREAD

**Issue by xxcriticxx** [a4k-openproject/script.module.openscrapers#11]
please remove as the following website are dead and don't exist anymore

```
<setting id="provider.openkatalog" type="bool" label="OPENKATALOG" default="false" />
<setting id="provider.paczamy" type="bool" label="PACZAMY" default="false" />
<setting id="provider.trt" type="bool" label="TRT" default="false" />
```

**Comment by A4K-Official** [comment]
Will do, working on removing dead providers soon and moving them off to different directories, ty for input

**Comment by xxcriticxx** [comment]
possible replacements:

`https://www.cda.pl/`
`https://plusfilm.pl/`
`http://filmbit.ws/`
`https://serialnet.pl/`
`https://filmowo.co/`
`http://serialosy24.pl/`
`https://allbox.tv/`
`https://kino123.pl/`
`http://filmosy.tv/`
`https://movieneo.com/`
`https://zalukaj.com/`
`https://virpe.com/`

**Comment by A4K-Official** [comment]
Deleted those links just in case but you know we need people who can find websites too. Mind messaging me on keybase? Redditreapercody is my handle

**Comment by A4K-Official** [comment]
ok fixed on dev branch
