### ISSUE TITLE
Hello from Germany

### ISSUE THREAD

**Issue by DWH-WFC** [a4k-openproject/script.module.openscrapers#118]
The german (de) scraper are almost all broken and should be revised.

**Comment by reddit-reaper** [comment]
@Tikipeter you think this is something up your alley? foreign hosters could really use some love

**Comment by Tikipeter** [comment]
@reddit-reaper 

I'm hoping to get to foreign eventually but unfortunately I've not got the skill set to fix scrapers so it's a hard slog for me. I've got some 'free' scrapers fixed ready for a PR. So hopefully foreign can be looked into soon. I'll start with the German ones when that's the case.
