### ISSUE TITLE
Furk scarper does not return any values

### ISSUE THREAD

**Issue by shieshe** [a4k-openproject/script.module.openscrapers#12]
I did a fresh install of the latest Exodus Redux. Disabled all other providers except Furk. Set up my login credentials and API key. Tried a search and got the notification that there was no stream found. My search on Furk.net itself returns plenty results. Did a test with the default providers and got back plenty of results. Looks like the Furk scraper is broken. Can you please look into this?

**Comment by A4K-Official** [comment]
In the Todo list! Ty for the report
