### ISSUE TITLE
Proposal for next update

### ISSUE THREAD

**Issue by 123Venom** [a4k-openproject/script.module.openscrapers#126]
I'm thinking next update to add the hash to our torrent sources dict.  Would make things a little easier for devs doing torrent cached/uncached checking, and or removal.

**Comment by jjred1977** [comment]
Speaking as an end user, I can only see this being beneficial to everybody
if you decide to implement it.

Thanks,

James J. Beuerlein

**Comment by 123Venom** [comment]
Currently working on next update and should have it finished up this coming weekend. cfscrape will be updated to v1.2.32(latest).  For all devs...torrents will now have `hash`, `seeders`, `name` added to sources dict.  The name is basically the `&dn=?` portion of the magnet link.  I now use this in Venom as a setting option vs. standard `Info` most exo forks use.
