### ISSUE TITLE
Venom displaying episode names instead of show titles in TV Shows/Calendar 

### ISSUE THREAD

**Issue by RickFromTexas** [a4k-openproject/script.module.openscrapers#129]
Seems to be displaying episode title rather than the name of the show. For example, Gold Rush: Parker's Trail show displayed as Hell's Crack: https://imgur.com/a/KN5rqjj

**Comment by drinfernoo** [comment]
That would be a Venom issue.

**Comment by RickFromTexas** [comment]
________________________________

**Comment by RickFromTexas** [comment]
My bad, thought I was on Venom's git.
________________________________
