### ISSUE TITLE
OpenScrapers v 0.0.1.109

### ISSUE THREAD

**Issue by marson53** [a4k-openproject/script.module.openscrapers#131]
Thanks for the update , was this update to fix  the cloudflare , cfscrape error , for me I'm still not getting any rlsbb links for some reason.

**Comment by 123Venom** [comment]
Looks like Venomous pushed a cfscrape update 6hrs ago and I gave that update package to reaper yesterday so it's not included obviously.  I also can confirm rlsbb is down and will have a look at it to get it back.  I'll try to get another update out for this fix by weekend.

**Comment by 123Venom** [comment]
well that was allot quicker and easier than I expected.  I updated OpenScrapers cfscrape to current v1.2.34 and rlsbb is back...was all in cfscrape and no scraper changes needed.  I'll get this over to reaper.  Might even cure some other oddities I've seen with some torrents throwing random bogus `Loop Protection` errors one minute and gone the next.

**Comment by 123Venom** [comment]
update pushed so closing

**Comment by marson53** [comment]
Thanks  for the update, works great , also got back a lot of my torrents working again , with being in the UK I have to use a lot of proxies for torrents and openscapers is the only I can get them to work with unblockit.one On 22 Apr 2020 6:13 p.m., 123Venom <notifications@github.com> wrote:
well that was allot quicker and easier than I expected.  I updated OpenScrapers cfscrape to current v1.2.34 and rlsbb is back...was all in cfscrape and no scraper changes needed.  I'll get this over to reaper.  Might even cure some other oddities I've seen with some torrents throwing random bogus Loop Protection errors one minute and gone the next.
