### ISSUE TITLE
OpenSSL error with cfscrape

### ISSUE THREAD

**Issue by chataigne73** [a4k-openproject/script.module.openscrapers#134]
Hello. Using openscrapers on Kodi 18.6 under windows 10.

When trying to scrape french yggtorrent website I get this error :

DEPRECATION: The OpenSSL being used by this python install (OpenSSL 1.0.2j  26 Sep 2016) does not meet the minimum supported version (>= OpenSSL 1.1.1) in order to support TLS 1.3 required by Cloudflare, You may encounter an unexpected reCaptcha or cloudflare 1020 blocks

And I can't bypass cloudfare protection.

Any idea ?

**Comment by A4K-Official** [comment]
we honestly havent updated other language scrapers in some time, maybe sometime in the future we can though

**Comment by 123Venom** [comment]
Little correction to this. The OpenSSL version in the Kodi 18 library is 1.0.2.  With that said until Kodi 19 comes along there's no update we can do to fix this.  That log error comes from cfscrape's OpenSSL version check.
