### ISSUE TITLE
Some scrapers not working in 0.0.2.003

### ISSUE THREAD

**Issue by Tinuz97** [a4k-openproject/script.module.openscrapers#140]
Like RLSbb, SceneRLS,Zoogle (just to name a few)
If i rollback to the previous version, they are working fine.

If you need a log, guide me.

Maybey you can replicate this issue also?

**Comment by bjbca** [comment]
Yes i noticed also that the attempt to make the Modules py3 compatible has broke almost all but torrent scrapers

**Comment by Tinuz97** [comment]
@Tikipeter , could this issue happened maybey because of the start of the python 3?

**Comment by 123Venom** [comment]
I'll look into this today but I seriously doubt the import changes Tikipete did has anything to do with it.  I know I pulled about 4-5 free hosters and 2 prem. hosters because they've gone v2 cloudflare challenge and we have no solution to solve that...notice rapidmoviez is gone?  It could be more have gone to this new v2 challenge as I feared that would happen, and more to come.  I'll let ya know what I find later today.

**Comment by Tinuz97** [comment]
> I'll look into this today but I seriously doubt the import changes Tikipete did has anything to do with it. I know I pulled about 4-5 free hosters and 2 prem. hosters because they've gone v2 cloudflare challenge and we have no solution to solve that...notice rapidmoviez is gone? It could be more have gone to this new v2 challenge as I feared that would happen, and more to come. I'll let ya know what I find later today.

Thx. 
I just use the previous version for now (rlsbb and scenerls working, also zoogle working fine in that one).

**Comment by 123Venom** [comment]
well actually there is a v2 challenge solve available but Venomous has opted to make it a paid subscription addon....he grew tired of his work being free.  We've been waiting it out to see how ugly this v2 challenge gets.

**Comment by Tinuz97** [comment]
> well actually there is a v2 challenge solve available but Venomous has opted to make it a paid subscription addon....he grew tired of his work being free. We've been waiting it out to see how ugly this v2 challenge gets.

Yeah, I did read that indeed (I follow VeNoMouS github also). 
But still weird that rlsbb and scenerls, zoogle working fine In the previous openscrapers version, so my guess is that it is not a V2 issue (I'm not a programmer, just using some logic), otherwise it should not work in the previous version I think? Just a thought.

**Comment by 123Venom** [comment]
> 
> 
> > I'll look into this today but I seriously doubt the import changes Tikipete did has anything to do with it. I know I pulled about 4-5 free hosters and 2 prem. hosters because they've gone v2 cloudflare challenge and we have no solution to solve that...notice rapidmoviez is gone? It could be more have gone to this new v2 challenge as I feared that would happen, and more to come. I'll let ya know what I find later today.
> 
> Thx.
> I just use the previous version for now (rlsbb and scenerls working, also zoogle working fine in that one).

That's odd...implies it's not a v2 challenge issue cause going backwards a version wouldn't get around that.

**Comment by 123Venom** [comment]
> 
> 
> > well actually there is a v2 challenge solve available but Venomous has opted to make it a paid subscription addon....he grew tired of his work being free. We've been waiting it out to see how ugly this v2 challenge gets.
> 
> Yeah, I did read that indeed (I follow VeNoMouS github also).
> But still weird that rlsbb and scenerls, zoogle working fine In the previous openscrapers version, so my guess is that it is not a V2 issue (I'm not a programmer, just using some logic), otherwise it should not work in the previous version I think? Just a thought.

ya sounds more like a code mistake....I need to just run some tests on it cause I swear those prem hosters were fine when tested but who knows.

**Comment by 123Venom** [comment]
ok..guys got me curious so took a work break.  Looks like it is an import error for py3.  Looking into it further but @Tikipeter? 

[2020-06-08 08:11:00] [COLOR red][ OPENSCRAPERS DEBUG ][/COLOR]: RLSBB - Exception: 
Traceback (most recent call last):
  File "C:\Users\Ken Brown\AppData\Roaming\Kodi\addons\script.module.openscrapers\lib\openscrapers\sources_openscrapers\en_DebridOnly\rlsbb.py", line 163, in sources
    url = client.replaceHTMLCodes(url)
  File "C:\Users\Ken Brown\AppData\Roaming\Kodi\addons\script.module.openscrapers\lib\openscrapers\modules\client.py", line 395, in replaceHTMLCodes
    return _replaceHTMLCodes(_replaceHTMLCodes(txt))
  File "C:\Users\Ken Brown\AppData\Roaming\Kodi\addons\script.module.openscrapers\lib\openscrapers\modules\client.py", line 400, in _replaceHTMLCodes
    txt = HTMLParser().unescape(txt)
TypeError: 'module' object is not callable

**Comment by Tinuz97** [comment]
I think you should remove the name (I see your name in the log, or maybey a name from  a work computer).,just a tip 😅

**Comment by 123Venom** [comment]
> 
> 
> I think you should remove the name (I see your name in the log, or maybey a name from a work computer).,just a tip 😅

ya woopsie..never pays to rush...see I shouldn't have taken a break and made you guys wait till I had time to focus...lol

**Comment by 123Venom** [comment]
@ Tikepete

Check me for client module change I'm doing but where you have 

# try:
	# import HTMLParser

I have

try:
	from HTMLParser import HTMLParser

**Comment by Tikipeter** [comment]
Yep, stuff up by your truly. I will make a pull request with a fix ASAP.

**Comment by 123Venom** [comment]
> 
> 
> Yep, stuff up by your truly. I will make a pull request with a fix ASAP.

shit happens brother.  You should see how many times I release a change to only release a fix for the fix..lol.  I'm the syntax error king!

**Comment by 123Venom** [comment]
and here's a list of scrapers lost to cloudflare v2 challenge thus far, and growing.

123movies
123movieshubz
fmovies
gomoviesonl
timewatch
rapidmoviez
tvdownloads
torrentz

mvrls was removed but site is dead and gone.
seriesonline was removed, but hCaptcha

prior updates removed others but allot of free hosters going wild javascript that I'm incapable of dealing with.

**Comment by Tinuz97** [comment]
Revert fixed it (version 0.0.2.004), thx.

**Comment by bjbca** [comment]
Just thought I would check in and offer up some praise for the great support from @123Venom and @Tikipeter , thanx for the endless hrs you guys pour into this stuff ;) im sure there are a tone of people out there who enjoy your efforts 👍
