### ISSUE TITLE
Using proxy sites

### ISSUE THREAD

**Issue by marson53** [a4k-openproject/script.module.openscrapers#142]
With being in the UK I have to use a lot of proxy sites to get torrents to scrape ,I used this  https://limetorrents.unblockit.me/  with openscrapers and others that used to work , but have stopped working sometime ago, is this because of cloudfare v2 change

**Comment by bjbca** [comment]
why not use a vpn provider, expressv** is a good one, there are cheaper but you get what you pay for some times...

**Comment by bjbca** [comment]
Also.. doesnt premiumize have a built in vpn service for paid account, that gets 2 birds with one stone ... a debrid type service that provides cached torrents and a vpn at same time.
