### ISSUE TITLE
SEEHD lost to v2 challenge

### ISSUE THREAD

**Issue by 123Venom** [a4k-openproject/script.module.openscrapers#143]
Cloudflare v2 challenge has taken another from us.  Will be removed in next update.

**Comment by bjgood** [comment]
yeah, doesn't look good. Venomous has put this hobby of ours in a hard spot.
Hopefully, someone will step forward to keep cfscrape free. But I would like to know how much he's asking.
Later. And thanks for all your hard work, dude.

**Comment by bjgood** [comment]
Someone posted a supposed pricing structure for Venomous cloudscraper service. If that's what he's wanting (per month) then it's way over what I'm willing to pay.
Later...

**Comment by 123Venom** [comment]
That's been about the general consensus I'm hearing as well.  Waiting things out to see how ugly it may or may not get.  Only torrent site I've seen go to the new cloudflare v2 challenge thus far is torrentz2, so I'm not crying just yet.
