### ISSUE TITLE
documentation for developing new scrapers

### ISSUE THREAD

**Issue by k2-br** [a4k-openproject/script.module.openscrapers#144]
Hello, I have been developing some scrapers using Bsoup for a while. I am interested in developing scrapers capable of being integrated with openscrapers. Is there documentation with clear instructions on how to develop scrapers to your pattern?

**Comment by bjbca** [comment]
seems like something @123Venom could answer

**Comment by 123Venom** [comment]
No real documentation.  Review current scrapers as a template and dive in.

**Comment by k2-br** [comment]
@123Venom, Is there a way to get the movie titles in pt-BR (Brazilian Portuguese) to search? Or only PT (Portugal)?
