### ISSUE TITLE
Filepursuit  Scraper

### ISSUE THREAD

**Issue by marson53** [a4k-openproject/script.module.openscrapers#148]
Hi just wanted to know if the Filepursuite Scraper still works
I have got the  api key from azharxes but not sure where to put the api key
Can you help ... Thanks

**Comment by 123Venom** [comment]
yes still works.  Go to accounts page..top item.

**Comment by marson53** [comment]
Thanks for the info, Finally I got it working

**Comment by 123Venom** [comment]
good deal
