### ISSUE TITLE
cfscrape not maintained anymore

### ISSUE THREAD

**Issue by sergio49** [a4k-openproject/script.module.openscrapers#149]
Hi, 

It seems cfscrape is not maintained anymore and is unable to bypass new cloudflare filtering. (IAM Error)

Would it be possible to integrate another version. I found this one which seems to work :
https://github.com/VeNoMouS/cloudscraper

Thanks and thank you for your great work

**Comment by 123Venom** [comment]
lol..cfscrape is Venomous's cloudscraper.  It's just a folder name change we did.  The version in openscrapers is 1.2.46 while Venomous's latest is 1.2.52.  I'm not so sure Venomous did any IUAM challenge changes in those versions.  Allot of what he changed what to the paid solve services.  Openscrapers has not been maintained in a spell.  Are you using Exodus Redux?  That's the only addon I believe using the package anymore.
