### ISSUE TITLE
ultrahdindir.py (developer branch) still not working

### ISSUE THREAD

**Issue by Tinuz97** [a4k-openproject/script.module.openscrapers#25]
ultrahdindir.py (i requested on Reddit a fix) is still not giving results back ,i replaced the old ultrahdindir.py with the new one from the developer branch, maybey you can also test this? Thx.

**Comment by reddit-reaper** [comment]
last i checked it was, will get it looked at thanks. @TheDevFreak can you take a look please

**Comment by reddit-reaper** [comment]
@Tinuz97 test new one, just updated from Eggs

**Comment by southpaw99** [comment]
Ok thanks

**Comment by Tinuz97** [comment]
Nope, maybey it is just me, no idea, but also with this eggs ultrahdindir scraper no results (installed the dev branch open meta scraper, in combination with exodus redux)

**Comment by reddit-reaper** [comment]
will have @TheDevFreak take a look later i reverted for now

**Comment by Tinuz97** [comment]
No problem, thx for trying anyway 👍

**Comment by TheDevFreak** [comment]
Still seems to work for me, do you have a debrid service enabled and linked?

**Comment by Tinuz97** [comment]
Yes, every other debrid scraper does work ok here, like rlsbb, invictus, ddlvalley as a few  example, are you testing with exodus redux also?

**Comment by reddit-reaper** [comment]
updated to a newer one, tested and working on my end
