### ISSUE TITLE
v 0.0.0.7 cfscrape

### ISSUE THREAD

**Issue by bjbca** [a4k-openproject/script.module.openscrapers#30]
v 0.0.0.7 the updated cfscrape seems to have broken rlsbb, way less premium links with rlsbb not working, i put the cfscrape from v 0.0.0.5 into v 0.0.0.7 and then rlsbb links are scraped and work

**Comment by A4K-Official** [comment]
Rlsbb shouldn't even be using it afaik but will check. There's a newer one now so we'll be updating again

**Comment by broknsymetry** [comment]
Also, cfscrape v1.9.7 opens a console window on Windows 10 for nodejs/node.exe for each scraper that includes the module.  Not really a bug, but it is annoying and may confuse/distress some users.

**Comment by reddit-reaper** [comment]
> Also, cfscrape v1.9.7 opens a console window on Windows 10 for nodejs/node.exe for each scraper that includes the module. Not really a bug, but it is annoying and may confuse/distress some users.

oh....dammit ok thanks i didnt see that happen on my end

**Comment by reddit-reaper** [comment]
@broknsymetry  try with latest version, just pushed out

**Comment by broknsymetry** [comment]
0.0.0.8 no more pop up console windows. 😄

**Comment by doko-desuka** [comment]
@reddit-reaper hi, where did you find that updated cfscrape?

**Comment by bjbca** [comment]
Working here, thank you ;)

**Comment by reddit-reaper** [comment]
> @reddit-reaper hi, where did you find that updated cfscrape?

In Yoda's script modules folder. Was trying to find a more updated one that worked but this was a quick fix, will most likely be adjusted soon enough

**Comment by doko-desuka** [comment]
Okay, thanks.
