### ISSUE TITLE
this repo trying to hijack or inject malicious code?

### ISSUE THREAD

**Issue by mgonzales71** [a4k-openproject/script.module.openscrapers#32]
https://github.com/nusch/nusch-repo/tree/master/script.module.openscrapers

version numbers are 9.x.x.x

seems kinda shady, I don't have a reddit account but maybe someone that does can post warning on addons4kodi (people should have auto updates off anyway)

**Comment by reddit-reaper** [comment]
as long as no one installs that bs repo its fine, people should know better
