### ISSUE TITLE
Foreign GERMAN providers

### ISSUE THREAD

**Issue by Maju3** [a4k-openproject/script.module.openscrapers#4]
Hi.
Can you check the german providers list please?
I use exodus redux and it loads no links when i set openscraper to use german providers.
BTW when i use lambdascrapers all works.
I have notized that in lambdascrapers the list of german providers is completely different.

**Comment by ChrisKar96** [comment]
The German providers listed are actually Greek.

**Comment by Maju3** [comment]
All right.
Thank you

**Comment by A4K-Official** [comment]
@I-A-C PR was merged so should be resolved. Issue closed :)
