### ISSUE TITLE
Torrent scraping broke after c06e458

### ISSUE THREAD

**Issue by host505** [a4k-openproject/script.module.openscrapers#40]
https://github.com/a4k-openproject/script.module.openscrapers/commit/c06e4586238a06eefe357745c30b47d7a39f3794
What is this `debrid.tor_enabled()` suppose to check? It breaks torrent scraping on my add-on, and exodus redux as well.
Removing [this check](https://github.com/a4k-openproject/script.module.openscrapers/blob/c06e4586238a06eefe357745c30b47d7a39f3794/lib/openscrapers/sources_openscrapers/en_Torrent/kickass2.py#L85-L86) from torrent scrapers makes them work again.
Are we supposed to implement an extra setting or something?
On a side note, this commit adds some lines with tabs, unlike the rest of the file's spaces indentation.

**Comment by A4K-Official** [comment]
it checks resolve URL to make sure you have the torrent option enabled. before they would just work regardless which isnt how it should work. all newer torrent scrapers are working like that now

**Comment by A4K-Official** [comment]
and crap will fix the indentation issue sorry about that

**Comment by host505** [comment]
Well it doesn't work (regardless of the indentation issue), I don't see how the resolveurl setting is connected to that check.

**Comment by A4K-Official** [comment]
ehhh also just realized my bad, i forgot to update the debrid.py thats why it wasnt working sigh will fix

**Comment by host505** [comment]
The reason that the video add-on's (eg Exodus redux's) torrent.enabled setting doesn't work with openscrapers is because your scrapers import openscrapers's debrid.py, which imports your control.py, which points to openscrapers's settings, and there doesn't exist a torrent.enabled setting.

**Comment by A4K-Official** [comment]
thanks. fixing all issues presented

**Comment by A4K-Official** [comment]
and you were correct i was wrong that it did not check with resolveURLs setting....sigh misunderstood

**Comment by A4K-Official** [comment]
ok just pushed a new build to dev branch. mind testing and letting me know if its working for you now

**Comment by host505** [comment]
Just tested on my phone, still won't work - you have to fix that tabs on the scrapers as well :)
 (afk right now so can't test thoroughly).
Also you might have to adjust line 43 to something like `if enabled == '' or enabled.lower() == 'true': return True`, so that it works ootb (since it's default true).

**Comment by A4K-Official** [comment]
im actually saying fuck it im changing it to work normally lol theres literally no need for that option now that i think about it so im removing that line from all torrent scrapers, debrid check only should be fine and will fix indent errors

**Comment by host505** [comment]
I'll agree to that, since you also have enable/disable all torrent scrapers.
But still the setting on Exodus resux eg won't work with openscrapers (I don't have that setting on my add-on).

**Comment by A4K-Official** [comment]
yeah exodus redux needs a few updates

**Comment by nazegnl** [comment]
I suggest you start using an IDE to prevent these issues in the future. I use PyCharm CE it'll help you maintain an consistent coding style aswell.

**Comment by A4K-Official** [comment]
@nazegnl yup im doing that now funnily enough.....question, spoke to another dev and he said the changes im wondering if i should push are fine but in PyCharm you can refactor code to fix a bunch of stuff like indents and imports formatting etc. it changes quite a few things up in....well pretty much everything lol wondering if i should push it or not though. And dammit man im still waiting for you to message me on some messenger ive given you my username on xD

**Comment by A4K-Official** [comment]
Well haven't pushed yet but got pretty much everything fixed along with some other things that Venom found that made some Torrent scrapers not work and missing modules etc. Thanks for all the help everyone :)

**Comment by nazegnl** [comment]
@A4K-Official If you make an PR we can have a look before you are merging.

**Comment by A4K-Official** [comment]
awesome thanks will do :)

**Comment by A4K-Official** [comment]
Fixed in e78899f74b73c6a86b2894d1c442e7944ab12e7a
