### ISSUE TITLE
Scrape Test Request & Issues

### ISSUE THREAD

**Issue by A4K-Official** [a4k-openproject/script.module.openscrapers#57]
Skip scrapers that require login like GoStream, Furk, etc

@nazegnl

**Comment by A4K-Official** [comment]
also running this command

scrape-test.py folders=en_Torrent test_type=1 test_mode=movie timeout_mode=false number_of_tests=50

doesnt check the folder listed, it is instead testing en and en_debridonly folders so its ignoring the argument

**Comment by A4K-Official** [comment]
@nazegnl looks like somehow the headers in the CSV Export for everything after RUNTIME are gone. Just letting you know

**Comment by nazegnl** [comment]
@A4K-Official I will check the tester tomorrow :)

**Comment by A4K-Official** [comment]
all good youve done alot so far :) so far i just notice that scrape_test is ignoring my command arguments lol like all of them unless you changed how theyre passed? anyways ill be patient :)

**Comment by nazegnl** [comment]
Checked the scraper-test.py and with me everything is working. 

For scrapers that do need login we could create a local setting file where you can store your private credentials.

**Comment by A4K-Official** [comment]
that works^

**Comment by A4K-Official** [comment]
are you running scraper test with arguments though or just straight? as none of my arguments i enter are testing correctly and now all scraper folders are being tested even when i only state en & en_DebridOnly

**Comment by nazegnl** [comment]
If there is nothing supplies it will test all folders. When you supply folder names you need to separate them with a comma. I use the example of the read.me file and is working for me.

**Comment by A4K-Official** [comment]
Do you use PC? I've tried both through my batch file and through cmd and neither are working anymore not sure why :-\

**Comment by nazegnl** [comment]
Yes, Windows PC will try you batch file later today.
