### ISSUE TITLE
vidics & xwatchseries

### ISSUE THREAD

**Issue by bjbca** [a4k-openproject/script.module.openscrapers#62]
just curious why vidics and xwatchseries are not being used because im getting a lot of links with them for episodes ?

**Comment by nazegnl** [comment]
Vidics was working for me the xwatchseries is not. Do you know what version of the scraper library you are refering to?

**Comment by bjbca** [comment]
when i get home i will try upload them for you

**Comment by nazegnl** [comment]
Thanks, Will have a look then.

**Comment by host505** [comment]
xwatchseries still exists on master branch (https://github.com/a4k-openproject/script.module.openscrapers/blob/master/lib/openscrapers/sources_openscrapers/en/to_be_fixed/no_sources/xwatchseries.py), but @nazegnl why did you delete it on your last pr?
Working here too btw

**Comment by bjbca** [comment]
Lets see if this works.

[vidics.xwatch.test.zip](https://github.com/a4k-openproject/script.module.openscrapers/files/3144902/vidics.xwatch.test.zip)

**Comment by nazegnl** [comment]
Readded both the scrapers again xwatschseries is giving for me with the scrape-test.py no results.

**Comment by bjbca** [comment]
Hmmm, I assume that whichever addon you use, you always clear provider cache after making a provider change, sometimes resetting function cache in resolveurl helps, or there is a flaw to scrapetest, heve you tried the scrapers "real world", for example, search for ray donovan season 5 Abby.

**Comment by bjbca** [comment]
Sorry i think i miss-understood.
