### ISSUE TITLE
Unresolved reference - Anilist

### ISSUE THREAD

**Issue by jabaxtor** [a4k-openproject/script.module.openscrapers#7]
The following scrapers all reference the missing module anilist:

Animeloads
Proxer
Foxx
Pureanime

This module will either need to be found or the providers removed

**Comment by A4K-Official** [comment]
ok remove it is

**Comment by A4K-Official** [comment]
@jabaxtor hey found anilist

https://github.com/I-A-C/script.module.exodusredux/tree/master/lib/resources/lib/modules
