### ISSUE TITLE
[Suggestion]Adding Headers on requests

### ISSUE THREAD

**Issue by bugatsinho** [a4k-openproject/script.module.openscrapers#71]
As title says, please add headers on the requests of cfscrape  to hide kodi headers.
In the case of client.request(url) headers are created inside the request function of client module so for example you dont need to set User-Agent in headers, but on normal requests and cfscrape requests you need to set User-Agent and possibly the baseurl as referer of the scraper to hide that way requests from kodi!
for example:

`scraper = cfscrape.create_scraper()
headers = {'User-Agent': client.agent(), 'Referer': self.base_url}
html = scraper.get(url, headers=headers).text`

**Comment by nazegnl** [comment]
Hi, the cfscrape class is setting headers on the request from a random set of predefined headers. So manually overwriting it is not necessary. I will add more headers to choose from so that it appears more random. About the referer it has no significant higher successrate in solving the js challenge.

**Comment by jewbmx** [comment]
Anorov just started updating his cfscrape again and has a nice useragent setup on it. My test showed it only worked on half the scrapers tho lol

**Comment by bugatsinho** [comment]
probably both  you missed my point.im not speaking about cfscrape requests I'm speaking in general for the requests...I'm not telling you how to solve the cf challenges.

**Comment by nazegnl** [comment]
I get your point, and agree with you that we need to mimic the the way the requests are made so we have don't stand out in the crowd. But cfscrape and the client implementation both have logic for random user agent selecting so only the referer could be something we need to add. But hen again there are more request headers we are lacking if we only implement referer for example.

**Comment by nazegnl** [comment]
@jewbmx yes noticed the update yesterday aswell, but it is using nodejs to solve the js challenge and therefore making it more difficult to be used in OpenScrapers as people need to install the dependency manually before they can start running the solution.

**Comment by bugatsinho** [comment]
ok guys thank you!
also this issue can be closed
