### ISSUE TITLE
Vidics is down

### ISSUE THREAD

**Issue by bjgood** [a4k-openproject/script.module.openscrapers#72]
Hi,
Just wanted to pass along that vidics is down. Could someone take a look at it?

Thanks.

**Comment by A4K-Official** [comment]
yup i know. im working on a final update to OpenScrapers v1 and should have it out by latest this weekend. v2 will be a massive change to a much more modern scraper system where scrapers arent 200+ lines anymore :) but that will be a bit as its a lot of work converting all old scrapers

**Comment by 123Venom** [comment]
I keep vidics disabled because it's problematic and cause lockups and bogs down the scrape.  It's not even a good source...throw it in the trash..lol

**Comment by bjgood** [comment]
Yeah, I know that vidics sucks big time but it's good for older, obscure series like Poirot, or Miss Marple, which the wife and I like to watch.

Version 2 sounds interesting. Looking forward to how you approach it.

**Comment by 123Venom** [comment]
Well the good news is I tested the dev branch, that I believe was pushed moments ago, and vidics now seems to no longer lock up the scrape process but I also onlyu tested a couple shows and could not return a source.  Hopefully your show works out for you

**Comment by bjgood** [comment]
Yes, I tested the dev branch as well, but it doesn't seem to work at all. It returns no results.

**Comment by A4K-Official** [comment]
from my tests, vidics isnt working in any addon atm as theyre all pretty much the same scraper. So might have to wait for v2

**Comment by bjgood** [comment]
Thanks, A4K-Official, for the update. It's much appreciated.

I'll close this issue and wait for version 2.

Again, thanks.

**Comment by A4K-Official** [comment]
well good news the main dev is taking a look at vidics before i drop this last v1 update

**Comment by A4K-Official** [comment]
nvm looks like they added captchas so not much we can do for now. gonna be removed from the next update

**Comment by bjgood** [comment]
yes, vidics has added a captcha before you can see the links to an episode. That sucks. About all you can do is monitor the site and see if they change their minds and drop it.

Very bright coders here. You've got a good thing going.

Thank you.

**Comment by A4K-Official** [comment]
ehhhh we have some ideas lol but definitely not until v2. If you know of any other sites that provide links like that email me at redditreaper@protonmail.com
