### ISSUE TITLE
the way to add openscrapers to a addon

### ISSUE THREAD

**Issue by twisted-fire-starter** [a4k-openproject/script.module.openscrapers#80]
hi i am having real trouble getting this to work i followed each step 4 times now and im still getting the same issue if you have a telegram group can you send me a invite please so maybe someone can help me get it to work please.

**Comment by reddit-reaper** [comment]
sorry about that been a bit busy. you know those instructions may be out of date will double check them to make sure. check back later tomorrow

**Comment by reddit-reaper** [comment]
i slightly updated the instructions but they seem to be good. Dont have a telegram group but you can reach me there at @jcpm90

**Comment by twisted-fire-starter** [comment]
> i slightly updated the instructions but they seem to be good. Dont have a telegram group but you can reach me there at @jcpm90

where is that i can find you at please pal ??

**Comment by twisted-fire-starter** [comment]
> i slightly updated the instructions but they seem to be good. Dont have a telegram group but you can reach me there at @jcpm90

i have sorted it budy thank you so much
