### ISSUE TITLE
how to i add some scrapers from a addon 

### ISSUE THREAD

**Issue by twisted-fire-starter** [a4k-openproject/script.module.openscrapers#85]
as title mentions i would like to be able to add some scrapers to openscrapers they are from a addon i have and i have tested to make sure they work and i have chacked to see if there is any duplicates and i have removed the duplicates as well

**Comment by drinfernoo** [comment]
If you'd like to contribute, you can open a PR with the proposed scrapers added.

**Comment by reddit-reaper** [comment]
yup just send a PR to dev branch and i will review and add @twisted-fire-starter

**Comment by reddit-reaper** [comment]
btw you can reach me on telegram, my username is @jcpm90
