### ISSUE TITLE
no result "https://movietown.org" branch "develop"

### ISSUE THREAD

**Issue by DevTeamLast01** [a4k-openproject/script.module.openscrapers#86]
url: https://movietown.org

use: "develop" Kodi on Firetvstick
The module "cfscrap.py" from branch "develop" does **NOT** return a result.

use: "develop" Kodi on windows
The module "cfscrap.py" from branch "develop" does return a result.

use: "master"
The same module "cfscrap.py" from branch "master" does return in Kodi a result on FireTvSick and on Windows

Sorry for the short text - my english is bad
Thank you
    
    url = https://movietown.org
    import openscrapers
    from openscrapers.modules import cfscrape
    scraper = cfscrape.create_scraper()
    sHtmlContent = scraper.get(url).content
    print sHtmlContent

**Comment by reddit-reaper** [comment]
sorry for the late reply will check

**Comment by reddit-reaper** [comment]
so the cfscrape module in develop should as it still passes all cloudflare tests. the only one that can not be gotten around is the google recaptcha one

**Comment by A4K-Official** [comment]
@DevTeamLast01 if you would like to reach me you can message me on telegram at @jcpm90
