### ISSUE TITLE
openscrapers settings revert on "ok"

### ISSUE THREAD

**Issue by bjbca** [a4k-openproject/script.module.openscrapers#9]
Here is a strange one, for example if i open scraper settings and choose disable all torrent providers it flashes and toggles them all off then i click "ok" and it exits out then when i go back in the torrents are all toggled back on, but if i disable all and then hit cancel to close settings and then go back in my changes will have been saved.... its as if Ok and Cancel are acting in reverse ? im using kodi 18.1

**Comment by A4K-Official** [comment]
@I-A-C Think theres an issue with the settings changes you made recently can you check them out please

**Comment by bjbca** [comment]
I dont know how much code has changed since civitas but im sure the problem existed in civitas, and it seems to happen mostly with the torrent section... have to test, maybe its something to do with defaults, the problem didn't happen with the original lambda module that i recall.

**Comment by bjbca** [comment]
tested... happens in all sections, in providers section I enable all then in Foreign I disable all, Debrid I enable all, Torrent I disable all, now if I click Ok the program exits and when I go back in none of those settings have been saved, then I go trough the cycle but at the end click cancel, the program exits and when I go back in my changes have been saved, all sections are affected.

**Comment by I-A-C** [comment]
I can't seem to replicate the situation where settings are not saved when click "Ok"

https://imgur.com/wPpdw6V

**Comment by bjbca** [comment]
I see, ok, are you in kodi 18.1 and could it have anything to do with the skin ? Im using estuary.

**Comment by I-A-C** [comment]
I'm using 17.6 with the confluence skin.  I'll take a look with estuary

**Comment by bjbca** [comment]
They only allow a 30sec vid... that was tough for me : <blockquote class="imgur-embed-pub" lang="en" data-id="a/4MWOmKR"><a href="//imgur.com/4MWOmKR"></a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

**Comment by I-A-C** [comment]
That 30sec limit is a pain.

Sure enough, I see what your talking about.  I'll take a closer look later.

**Comment by A4K-Official** [comment]
@I-A-C thanks man :)

**Comment by 123Venom** [comment]
I've seen this problem in Civitas under Kodi 18 & 18.1.  I just now tested it with Redux using the open scrapers and did exactly as in the video yet the options were not flipped.  Last time I tried to debug this , in Civitas, I noticed it worked if I used the "Diasable, or Enable,  All Providers" then used the individual category enable options.  I had looked at the code awhile back and thought I had an idea how to cure it as I saw the code difference the "Enable/Disable All" did vs. just the toggle def section.  I'd have to refreshen my brain on the matter again as I never did take the time to experiment with a fix.

**Comment by 123Venom** [comment]
I just tested to the little work around I had done with Civitas that seemed to work but not so anymore.  I even tried using "OpenScraper Default Providers" then trying to enable/disable individual categories...still a no go on saving it.  Displays right but hitting "ok" then returning and they're still off.  Seems to be an issue saving them.  I flipped to Estuary skin under 18.1 and it saves and works fine.  I also tested with Aura skin and again it's fine.  Must be something up with the Nox:Silvo skin because that's were it fails to me.

**Comment by A4K-Official** [comment]
Interesting....hmm. I'm having a guy that's good with settings xml take a look so hopefully fixed soon

**Comment by jewbmx** [comment]
I didnt read all of this but from my exper. with a enable all setting it needs to have the close action completely removed so it stays open. That usually helps, but it is pretty common on my use of it that its glitchy anyways and will save most the time lol.  Yall might be able to work around any ok button issues with this tho if its a problem too..  `
    execute = xbmc.executebuiltin
    execute('Dialog.Close(okdialog, true)')
`

**Comment by reddit-reaper** [comment]
Settings issue fixed in latest update
