### ISSUE TITLE
Digbt.py Crashes Dialog Box with Results

### ISSUE THREAD

**Issue by pewkodi** [a4k-openproject/script.module.openscrapers#92]
I am having an issues with  digbt.py causing the dialog window to not show other links. I have tested it with a working one and that one only available in the folder and it will prevent the dialog box from coming up. if I comment out the self variables it will work correctly(with no links from digbt). I noticed it was a cf based and are always hard to fix at times.  I just wanted to see if you can confirm as well.

Thanks

**Comment by reddit-reaper** [comment]
i havent seen any changes for that scraper in the wild but i have updated cfscrape on develop branch. give it a run and see if it works better for you now. remember to always reset settings to default and clear providers in your addon of choice before testing
