### ISSUE TITLE
v.195, 2ddl and rapidmoviez

### ISSUE THREAD

**Issue by bjbca** [a4k-openproject/script.module.openscrapers#93]
2ddl giving this error: http://2ddl.vg/ returned an error. Could not collect tokens.

and rapidmoviez requires "from openscrapers.modules import dom_parser2" but dom_parser2.py is not in modules, i was able to add my own dom_parser2 but i thought i would let you know.

**Comment by reddit-reaper** [comment]
ty for the report. idk how i missed that. fixing

**Comment by reddit-reaper** [comment]
ok should be fixed in the latest github push on the develop branch
