### ISSUE TITLE
user_agents.py

### ISSUE THREAD

**Issue by bjbca** [a4k-openproject/script.module.openscrapers#94]
v196 seem to be having trouble with user agents py, may just be me, had to revert to last cfscrape etc as scrapers cant load user_agents.py

**Comment by bjbca** [comment]
i think i found it here
https://github.com/a4k-openproject/a4kScrapers/blob/master/providerModules/a4kScrapers/third_party/user_agents.py

**Comment by reddit-reaper** [comment]
you are correct, file mustve downloaded wrong when i grabbed it. thanks will fix
