### ISSUE TITLE
v197 en onlineseries

### ISSUE THREAD

**Issue by bjbca** [a4k-openproject/script.module.openscrapers#96]
Sorry, I forgot to mention, that there is a copy of onlineseries in en that still calls for dom_parser2, the one in en_debrid_only is proper and i guess the one in en should be removed.
  And just a thank you for creating and maintaining openscrapers ;)

**Comment by reddit-reaper** [comment]
Ugh wtf lol i did a search and i didn't see that lol will fix when i get up

**Comment by reddit-reaper** [comment]
And thanks for finding issues :)
