### ISSUE TITLE
problems with many german scraper sites

### ISSUE THREAD

**Issue by Stimmenhotel** [a4k-openproject/script.module.openscrapers#99]
Really many german scraper seems to be broken.
I used venom with only the foreign scrapers and set to german indexers within venom.

right now I have only found sources at iload, ddl(.me?) and streamto.
I know the searched series is at least at serienstream (s.to), freikino, hdfilme, kinox.to.

Could someone look into this?

Or anyone has a "easy" guide for making scrapers, than I could try it myself. 
(Haven't done this before, nor used python much)

**Comment by 3lementX** [comment]
discreet push

Would be great if the German providers will work!
